version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ecto
    versions:
    - 3.5.6
    - 3.5.7
    - 3.5.8
    - 3.6.0
  - dependency-name: ex_doc
    versions:
    - 0.23.0
    - 0.24.0
    - 0.24.1
  - dependency-name: earmark
    versions:
    - 1.4.13
    - 1.4.14
  - dependency-name: castore
    versions:
    - 0.1.9
  - dependency-name: db_connection
    versions:
    - 2.3.1
